print('CALCULADORA')
print("Operações disponíveis:")
print("1. Soma")
print("2. Subtração")
print("3. Multiplicação")
print("4. Divisão")
print("5. Raiz Quadrada")
print("6. Seno")
print("7. Cosseno")
